FROM ubuntu:16.04

RUN apt-get update && \
	apt-get install -y \
	build-essential \
	cmake \
	git \
	vim \
    wget \
    unzip \
    yasm \
    g++ \
    pkg-config \
	libavcodec-dev \
    libavformat-dev \
    libswscale-dev \
    libtbb2 \
    libtbb-dev \
    libjpeg-dev \
    libpng-dev \
    libtiff-dev \
    libjasper-dev \
    libavformat-dev \
    libpq-dev \
    libgtk2.0-dev \
    libopencv-dev \
    liblapack-dev \
    libdlib-dev
